### PR TITLE
react native dependency upgrade

### PR DESCRIPTION
**Pull request by tyler-whitman**
- react native 0.70.1
- expo 46
- helium libs to latest

### CODE REVIEW

**Review by Perronef5 — COMMENTED** [review]
Getting this on my M1. Not sure if its building for @matthewcarlreetz 

Screen Shot 2022-09-28 at 11 22 31 AM

**Comment by tyler-whitman** [comment]
Hmm maybe hermes iOS isnt working on M1. Could you guys try setting hermes to false in the pod file? Also maybe try a `yarn clean-install`?

**Comment by tyler-whitman** [comment]
Oh there is a 0.70.1 now too, maybe that will fix it. Let me update

**Comment by tyler-whitman** [comment]
@Perronef5 can you test with @matthewcarlreetz change, it should work now. Tested on intel and its working for me too

**Comment by Perronef5** [comment]
> @Perronef5 can you test with @matthewcarlreetz change, it should work now. Tested on intel and its working for me too

I keep getting expo modues not found error now :/ 

```
error build: module map ExpoModulesCore/ExpoModulesCore.modulemap' not found
```

**Comment by tyler-whitman** [comment]
> > @Perronef5 can you test with @matthewcarlreetz change, it should work now. Tested on intel and its working for me too
> 
> I keep getting expo modues not found error now :/
> 
> ```
> error build: module map ExpoModulesCore/ExpoModulesCore.modulemap' not found
> ```

Did you try a `clean-install`? If that doesnt work maybe delete your derived data `rm -rf ~/Library/Developer/Xcode/DerivedData`

**Comment by Perronef5** [comment]
> > > @Perronef5 can you test with @matthewcarlreetz change, it should work now. Tested on intel and its working for me too
> > 
> > 
> > I keep getting expo modues not found error now :/
> > ```
> > error build: module map ExpoModulesCore/ExpoModulesCore.modulemap' not found
> > ```
> 
> Did you try a `clean-install`? If that doesnt work maybe delete your derived data `rm -rf ~/Library/Developer/Xcode/DerivedData`

Yaa I did all of that

**Review by Perronef5 — APPROVED** [review]

**Pull request merged**
